blog/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', views.post, name='post'),
    url(r'^', views.posts, name='posts'),
]

book/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView

from rest_framework import routers

import users.views as users_views
import books.views as books_views
import api.views as api_views
import posts.views as posts_views
import activities.views as activities_views
import basic.views as basic



favicon_view = RedirectView.as_view(url='/static/icons/favicon.ico', permanent=True)

router = routers.DefaultRouter()
router.register(r'books', api_views.BookViewSet)
router.register(r'reviews', api_views.ReviewViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^react/', TemplateView.as_view(template_name="index.html")),
    url(r'^api', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^settings/$', users_views.settings, name='settings'),
    url(r'^books/', include('books.urls')),
    url(r'^notifications/$', activities_views.notifications, name='notifications'),
    url(r'^(?P<username>[\w.@]+)/$', users_views.profile, name='profile'),
    url(r'^(?P<username>[\w.@]+)/followers/$', users_views.profile_followers, name='profile_followers'),
    url(r'^(?P<username>[\w.@]+)/following/$', users_views.profile_following, name='profile_following'),
    url(r'^(?P<username>[\w.@]+)/info/$', users_views.profile_info, name='profile_info'),
    url(r'^(?P<username>[\w.@]+)/favourite-books/$', users_views.profile_fav_books, name='profile_fav_books'),
    url(r'^$', users_views.home, name='home'),
    url(r'^privacy-policy/$', basic.policy, name='privacy-policy'),
    url(r'^users/follow/$', users_views.user_follow, name='user_follow'),
    url(r'^b/add-fav/$', books_views.add_fav, name='add_fav'),
    url(r'^p/like/$', posts_views.post_like, name='post_like'),
    url(r'^r/like/$', books_views.review_like, name='review_like'),
    url(r'^r/delete/$', books_views.review_delete, name='review_delete'),
    url(r'^r/comment/$', books_views.review_comment, name='review_comment'),
    url(r'^r/comment/delete/$', books_views.comment_delete, name='review_comment_delete'),
    url(r'^b/add/$', books_views.book_create, name='create'),
    url(r'^p/post/$', posts_views.post_write, name='write'),
    url(r'^p/comment/$', posts_views.post_comment, name='post_comment'),
    url(r'^p/comment/delete/$', posts_views.comment_delete, name='post_comment_delete'),
    url(r'^p/(?P<id>\d+)/$', posts_views.post_detail, name='post_detail'),
    url(r'^p/delete/$', posts_views.post_delete, name='post_delete'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^user/menu/$', basic.user_menu,
        name='user_menu'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='book'),
    url(r'^$', views.list, name='books'),
]

books/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.utils.text import slugify
from datetime import datetime
from django.utils.timezone import now as timezone_now
import os
from django.utils import timezone
from ckeditor.fields import RichTextField
from users.models import Profile
from activities.models import Activity
import unidecode
from unidecode import unidecode
from taggit_autosuggest.managers import TaggableManager


def upload_to(instance, filename):
    now = timezone_now()
    filename_base, filename_ext = os.path.splitext(filename)
    return "books/%s%s" % (now.strftime("%Y/%m/%Y%m%d%H%M%S"), filename_ext.lower(),)


class Book(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    first_published = models.DateField(blank=True, null=True)
    publisher = models.CharField(max_length=200, blank=True, null=True)
    ISBN = models.CharField(max_length=50, blank=True, null=True)
    edition = models.CharField(max_length=100, blank=True, null=True)
    page_count = models.IntegerField(blank=True, null=True)
    author = models.CharField(max_length=200)
    user = models.ForeignKey(User, related_name="books_added")
    genre = TaggableManager(verbose_name="Genre", help_text="Select from suggestions as you type the name of the genre. If there is no genre you are looking for type comma after writing it.", through=None, blank=False)
    about = RichTextField()
    language = models.CharField(max_length=200)
    original_language = models.CharField(max_length=200, blank=True, null=True)
    cover = models.ImageField(upload_to=upload_to, null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_date',)
        verbose_name = 'Book'
        verbose_name_plural = 'Books'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super(Book, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('book', args=[self.slug])


class Review(models.Model):
    book = models.ForeignKey(Book, related_name='reviews')
    user = models.ForeignKey(User, related_name='reviews')
    review = RichTextField()
    date = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return 'Review by {} on {}'.format(self.user, self.book)

    def calculate_likes(self):
        likes = Activity.objects.filter(activity_type=Activity.LIKE,
                                        review=self.pk).count()
        self.likes = likes
        self.save()
        return self.likes

    def get_likes(self):
        likes = Activity.objects.filter(activity_type=Activity.LIKE,
                                        review=self.pk)
        return likes

    def get_likers(self):
        likes = self.get_likes()
        likers = []
        for like in likes:
            likers.append(like.user)
        return likers


class Comment(models.Model):
    review = models.ForeignKey(Review, related_name='comments')
    user = models.ForeignKey(User, related_name='comments_on_reviews')
    comment = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('-date',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user, self.review)

    def calculate_likes(self):
        likes = Activity.objects.filter(activity_type=Activity.LIKE,
                                        review=self.pk).count()
        self.likes = likes
        self.save()
        return self.likes

    def get_likes(self):
        likes = Activity.objects.filter(activity_type=Activity.LIKE,
                                        review=self.pk)
        return likes

    def get_likers(self):
        likes = self.get_likes()
        likers = []
        for like in likes:
            likers.append(like.user)
        return likers


class Favourite(models.Model):
    profile = models.ForeignKey(Profile, related_name='fav_from_set', null=True)
    book = models.ForeignKey(Book, related_name='fav_to_set')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} likes {}'.format(self.profile, self.book)


# Add following field to User dynamically

users/models.py
from django.db import models
from django.conf import settings 
from django.contrib.auth.models import User
import urllib
import hashlib
import os.path
from django.db.models.signals import post_save
from django.utils.timezone import now as timezone_now
from activities.models import Notification


def upload_to(instance, filename):
    now = timezone_now()
    filename_base, filename_ext = os.path.splitext(filename)
    return "profile/%s%s" % (
        now.strftime("%Y/%m/%Y%m%d%H%M%S"),
        filename_ext.lower(),)


def upload_back(instance, filename):
    now = timezone_now()
    filename_base, filename_ext = os.path.splitext(filename)
    return "profile/back_image/%s%s" % (
        now.strftime("%Y/%m/%Y%m%d%H%M%S"),
        filename_ext.lower(),)


class Profile(models.Model):
    user = models.OneToOneField(User)
    about = models.TextField(max_length=200, blank=True, null=True)
    url = models.CharField(max_length=50, null=True, blank=True)
    avatar = models.ImageField(upload_to=upload_to, null=True, blank=True)
    back_image = models.ImageField(upload_to=upload_back, null=True, blank=True)
    fav_books = models.ManyToManyField('books.Book', through='books.Favourite')
    # reputation = models.IntegerField(default=0)
    # language = models.CharField(max_length=5, default='en')

    class Meta:
        db_table = 'auth_profile'

    def get_url(self):
        url = self.url
        if "http://" not in self.url and "https://" not in self.url and len(self.url) > 0:
            url = "http://" + str(self.url)

        return url

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username

    def notify_liked(self, post):
        if self.user != post.user:
            Notification(notification_type=Notification.LIKED,
                         from_user=self.user, to_user=post.user,
                         post=post).save()

    def notify_followed(self, user):
        if self.user != user:
            Notification(notification_type=Notification.FOLLOWED,
                         from_user=self.user, to_user=user,
                         user=user).save()

    def unotify_followed(self, user):
        if self.user != user:
            Notification.objects.filter(notification_type=Notification.FOLLOWED,
                         from_user=self.user, to_user=user,
                         user=user).delete()
            
    def notify_commented(self, post):
        if self.user != post.user:
            Notification(notification_type=Notification.COMMENTED,
                         from_user=self.user, to_user=post.user,
                         post=post).save()

    def unotify_commented(self, post):
        if self.user != post.user:
            Notification.objects.filter(notification_type=Notification.COMMENTED,
                         from_user=self.user, to_user=post.user,
                         post=post).delete()             

    def notify_review_liked(self, review):
        if self.user != review.user:
            Notification(notification_type=Notification.REVIEW_LIKED,
                         from_user=self.user, to_user=review.user,
                         review=review).save()

    def unotify_review_liked(self, review):
        if self.user != review.user:
            Notification.objects.filter(notification_type=Notification.REVIEW_LIKED,
                         from_user=self.user, to_user=review.user,
                         review=review).delete()

    def notify_post_liked(self, post):
        if self.user != post.user:
            Notification(notification_type=Notification.POST_LIKED,
                         from_user=self.user, to_user=post.user,
                         post=post).save()

    def unotify_post_liked(self, post):
        if self.user != post.user:
            Notification.objects.filter(notification_type=Notification.POST_LIKED,
                         from_user=self.user, to_user=post.user,
                         post=post).delete()

    def notify_image_liked(self, image):
        if self.user != image.user:
            Notification(notification_type=Notification.IMAGE_LIKED,
                         from_user=self.user, to_user=image.user,
                         image=image).save()

    def unotify_image_liked(self, image):
        if self.user != image.user:
            Notification.objects.filter(notification_type=Notification.IMAGE_LIKED,
                                        from_user=self.user, to_user=image.user,
                                        image=image).delete()

    def notify_image_commented(self, image):
        if self.user != image.user:
            Notification(notification_type=Notification.IMAGE_COMMENTED,
                         from_user=self.user, to_user=image.user,
                         image=image).save()

    def unotify_liked(self, post):
        if self.user != post.user:
            Notification.objects.filter(notification_type=Notification.LIKED,
                                        from_user=self.user, to_user=post.user,
                                        post=post).delete()           

    def notify_also_commented(self, feed):
        comments = feed.get_comments()
        users = []
        for comment in comments:
            if comment.user != self.user and comment.user != feed.user:
                users.append(comment.user.pk)

        users = list(set(users))
        for user in users:
            Notification(notification_type=Notification.ALSO_COMMENTED,
                         from_user=self.user,
                         to_user=User(id=user), feed=feed).save()

    def notify_favorited(self, question):
        if self.user != question.user:
            Notification(notification_type=Notification.FAVORITED,
                         from_user=self.user, to_user=question.user,
                         question=question).save()

    def unotify_favorited(self, question):
        if self.user != question.user:
            Notification.objects.filter(
                notification_type=Notification.FAVORITED,
                from_user=self.user,
                to_user=question.user,
                question=question).delete()

    def notify_answered(self, question):
        if self.user != question.user:
            Notification(notification_type=Notification.ANSWERED,
                         from_user=self.user,
                         to_user=question.user,
                         question=question).save()

    def notify_accepted(self, answer):
        if self.user != answer.user:
            Notification(notification_type=Notification.ACCEPTED_ANSWER,
                         from_user=self.user,
                         to_user=answer.user,
                         answer=answer).save()

    def unotify_accepted(self, answer):
        if self.user != answer.user:
            Notification.objects.filter(
                notification_type=Notification.ACCEPTED_ANSWER,
                from_user=self.user,
                to_user=answer.user,
                answer=answer).delete()


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)


class Contact(models.Model):
    user_from = models.ForeignKey(User,related_name='rel_from_set')
    user_to = models.ForeignKey(User, related_name='rel_to_set')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)


# Add following field to User dynamically
User.add_to_class('following',
                  models.ManyToManyField('self',
                                         through=Contact,
                                         related_name='followers',
                                         symmetrical=False))

books/templates/books/books.html
{% load i18n %}

	<div style="width:100%; max-width:1300px;" class="clearer">
        {% for book in books %}
		<div style="padding:2px; margin-top:20px;" class="list">
		    <div style="width:100%;" class="clearer w3-white w3-left border-all">
                <div class="book-list" style="width:50%; float:left;">
                    <a href="{% url 'book' book.slug %}">
                        <div style="width:100%; height:100%; position:absolute; background-image: url('https://libercen.s3.amazonaws.com/{{book.cover}}'); background-position: center top; background-repeat: no-repeat; background-size:cover;">
                        </div>
                    </a>
                </div>
                <div style="margin-left:5px; padding:3px; float:left; width:48%;">
                    <a href="{% url 'book' book.slug %}"><b>{{ book.name }}</b></a>
                    <p><i>by {{ book.author }}</i></p>
                    {% with total_users_liked=book.profile_set.count %}
                        <span class="count">
                        <span class="total">{{ total_users_liked }}</span>
                            user{{ total_users_liked|pluralize }} liked
                        </span>
                        <button data-id="{{ book.id }}" data-action="{% if book in request.user.profile.fav_books.all %}un{% endif %}fav" style="color:white; font-size:12px;" class="w3-round w3-btn custom-{% if book in request.user.profile.fav_books.all %}red{% else %}green{% endif %} fav button">
                        {% if book not in request.user.profile.fav_books.all %}
                            Add to favourites
                        {% else %}
                            Remove from favourites
                        {% endif %}
                        </button>
		            {% endwith %}
                </div>
			</div>
		</div>
        {% empty %}
        <h1>Empty</h1>
        {% endfor %}
	</div>

books/templates/books/create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block head %}
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<link href="/static/jquery-autosuggest/css/autoSuggest.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/jquery-autosuggest/js/jquery.autoSuggest.minified.js"> </script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<style>
    .form-control { width:100%; }
    #id_genre__tagautosuggest { height:auto!important; }
</style>
  <script>
  $( function() {
    $( "#id_first_published" ).datepicker();
  } );
  </script>

{% endblock %}



{% block content %}

<div style="margin-top:30px; max-width:700px; width:90%; margin:10px auto; border:1px solid grey; padding:10px; background-color: #efecec;" class="w3-container w3-white">
    <div>
        <h2>Add a new book</h2>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
              {{hidden}}
            {% endfor %}

            {% for field in form.visible_fields %}
            <div class="form-group">
              {% for error in field.errors %}
              <div class="alert alert-danger" >{{ error }}</div>
            {% endfor %}
            <label for="{{ field.id_for_label }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>{{ field|add_class:'form-control' }}
            <p class="form-text text-muted">{{ field.help_text }}</p>
            </div>  
            {% endfor %}
            <input class="w3-btn w3-round custom-blue" style="box-shadow:none; color:white" type="submit" value="Add book">
        </form>
    </div>
</div>

{% endblock %}

books/templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ book.name }}{% endblock title %}

{% block head %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<style>
	.square {
		position: relative;
		width: 100%;
		border-radius: 3px;

	}

	.square:after {
		content: "";
		display: block;
		padding-bottom: 100%;
	}
	.square-cover {
		position: relative;
		width: 25%;
		border-radius: 3px;

	}

	.square-cover:after {
		content: "";
		display: block;
		padding-bottom: 160%;
	}

	.image {
		position: absolute;
		background-image: url('http://libercen.s3.amazonaws.com/{{book.cover}}');
		background-position: center center;
		background-repeat: no-repeat;
		background-size: cover;
		width: 100%;
		height: 100%;
	}
	.clearer{
		clear:both;overflow:hidden;
	}
	.form-control {
		width:100%;
	}
	.small-profile {
		position: absolute;
		background-position: center center;
		background-repeat: no-repeat;
		background-size:cover;
		width: 100%;
		height: 100%;
	}



</style>
<script>

</script>
{% endblock %}



{% block content %}
<div class="border-all" style="margin-top:30px; max-width:800px; width:90%; margin:10px auto;background-color: white;">
	{% if messages %}
	{% for message in messages %}
	<div>
		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			{{ message }}
		</div>
	</div>
	{% endfor %}
	{% endif %}
	<div class="clearer w3-padding">
		<div class="square-cover border-all" style="float:left;">
			<div class="image"></div>
		</div>
		<div style="float:left; padding-left:10px; width:74%;">
			<p class="w3-large"><strong>{{book.name}}</strong></p>

			{% with total_users_liked=book.profile_set.count %}
				<span class="count">
				<span class="total">{{ total_users_liked }}</span>
					user{{ total_users_liked|pluralize }} liked
				</span>
				<button data-id="{{ book.id }}" data-action="{% if book in request.user.profile.fav_books.all %}un{% endif %}fav" class="w3-round w3-btn custom-{% if book in request.user.profile.fav_books.all %}red{% else %}green{% endif %} fav button">
				{% if book not in request.user.profile.fav_books.all %}
					Add to favourites
				{% else %}
					Remove from favourites
				{% endif %}
				</button>
			{% endwith %}

			<p style="margin-top:15px;"><strong>Author: </strong>{{book.author}}</p>

			{% if book.publisher %}
				<p><strong>Publisher: </strong>{{ book.publisher }}</p>
			{% endif %}

			{% if book.published %}
				<p><strong>Published: </strong>{{ book.published }}</p>
			{% endif %}

			{% if book.page_number  %}
				<p><strong>Page count: </strong>{{ book.page_number }}</p>
			{% endif %}

			<p>{{book.about|safe|linebreaks}}</p>
		</div>
	</div>
	<hr>
	<h4 class="w3-center">Add your review about the book</h4>
	<form action="." method="post" class="w3-padding">
		<div style="margin-top:10px; margin-bottom:20px;">
			{{ review_form.as_p }}
			{% csrf_token %}
			<p><input class="w3-btn w3-round custom-green" style="box-shadow:none; color:white" type="submit" value="Add review"></p>
		</div>
	</form>
	{% if reviews %}
    <h4 class="w3-center">Reviews</h4>
	<div class="review-list">
		{% include 'books/reviews.html' with reviews=reviews %}
	</div>
	{% endif %}
</div>




{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#review-list').append(data);
    	        }
            });
    	}
    });
	$('button.fav').click(function(e){
		e.preventDefault();
		var div = $(this).closest("div");
		$.post('{% url "add_fav" %}',
			{
				id: $(this).data('id'),
				action: $(this).data('action')
			},
			function(data){
				if (data['status'] == 'ok') {
					var previous_action = $('button.fav').data('action');
					// toggle data-action
					$('button.fav').data('action',
					previous_action == 'fav' ? 'unfav' : 'fav');
					// toggle link text
					$('button.fav').text(
					previous_action == 'fav' ? 'Remove from favourites' : 'Add to favourites');
					// update total followers
					var previous_favers = parseInt(
					$('span.count .total').text());
					$('span.count .total').text(previous_action == 'fav' ?
					previous_favers + 1 : previous_favers - 1);
					if (previous_action == 'fav') {
						$('button.fav', div).removeClass('custom-green');
						$('button.fav', div).addClass('custom-red');
					}
          			else {
						$('button.fav', div).removeClass('custom-red');
						$('button.fav', div).addClass('custom-green');
					}

				}
			}
		);
	});

	$("ul.review-ul").on("click", ".like", function () {
		var li = $(this).closest("li");
		var review = $(li).attr("review-id");
		var csrf = $(li).attr("csrf");
		$.ajax({
		  url: '/r/like/',
		  data: {
			'review': review,
			'csrfmiddlewaretoken': csrf
		  },
		  type: 'post',
		  cache: false,
		  success: function (data) {
			if ($(".like", li).hasClass("unlike")) {
			  $(".like", li).removeClass("unlike");
			  $(".like .fa", li).removeClass("fa-thumbs-up")
			  $(".like .fa", li).addClass("fa-thumbs-o-up");
			  $(".like .text", li).text("Like");
			}
			else {
			  $(".like .fa", li).addClass("fa-thumbs-up");
			  $(".like .fa", li).removeClass("fa-thumbs-o-up");
			  $(".like", li).addClass("unlike");
			  $(".like .text", li).text("Unlike");
			}
			$(".like-count", li).text(data);
			$(".like .fa", li).addClass(data);
			$(".like .fa", li).removeClass(data);
		  }
		});
		return false;
	  });

	  $("ul.review-ul").on("click", ".review-delete", function () {
		var li = $(this).closest("li.review-li");
		var review = $(li).attr("review-id");
		var csrf = $(li).attr("csrf");
		var div = $(this).closest("div.review")
		$.ajax({
		  url: '/r/delete/',
		  data: {
			'review': review,
			'csrfmiddlewaretoken': csrf
		  },
		  type: 'post',
		  cache: false,
		  success: function (data) {
			$(div).fadeOut(400, function () {
			  $(div).remove();
			});
		  }
		});
	  });
		function review_comment(review, csrf, li) {
			$.ajax({
				url : "/r/comment/",
				type : "POST",
				data : {
					'comment' : $('.comment-text', li).val(),
					'review' : review,
					'csrfmiddlewaretoken': csrf
				},

				// handle a successful response
				success : function(json) {
					$('.comment-text', li).val(''); // remove the value from the input
					console.log(json); // log the returned json to the console
					if (json.useravatar) {
						var avatarUrl = json.useravatar
					}
					else {
						var avatarUrl = "/static/icons/no-image.jpg"
					}
					$('.comments-list', li).prepend('<div class="clearer" comment-id="' + json.commentpk + '" csrf="{{ csrf_token }}"><div style="padding:10px; float:left; width:97%;" class="clearer"><div class="square w3-round" style="float:left; border: 1px solid grey; width:5%;"><div style="float:left; background-image: url(' + avatarUrl + ');" class="w3-round small-profile"></div></div><div class="w3-white" style="width:94%; padding:10px; float:right; border-radius:15px;"><p><a href="/' + json.user + '/" >' + json.user + ' </a>' + json.comment + '</p></div></div><button class="comment-delete w3-btn w3-left"><i class="fa fa-times"></i></button></div>');
				},
				// handle a non-successful response
				error : function(xhr,errmsg,err) {
					$('.results', li).html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
						" <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
					console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
				}
			});
		};
		$('.commentForm').on('submit', function(event){
			event.preventDefault();
			var li = $(this).closest("li");
			var review = $(li).attr("review-id");
			var csrf = $(li).attr("csrf");
			review_comment(review, csrf, li);
		});

		$(".comment-delete").on("click", function () {
			var div = $(this).closest("div");
			var comment = $(div).attr("comment-id");
			var csrf = $(div).attr("csrf");
			$.ajax({
			  url: '/r/comment/delete/',
			  data: {
				'comment': comment,
				'csrfmiddlewaretoken': csrf
			  },
			  type: 'post',
			  cache: false,
			  success: function (data) {
				$(div).fadeOut(400, function () {
				  $(div).remove();
				});
			  }
			});
		  });

{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}


{% block head %}

<style>
    .book-list {
        position:relative;
        width:100%;

    }
    .book-list:after {
        content:"";
        display:block;
        padding-bottom:158%;

    }
    .list {
        width:33%;
        float:left;

    }
</style>

{% endblock head %}


{% block content %}

<div class="w3-container">
    <div id="book-list">
        {% include "books/books.html" %}
    </div>
</div>

{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#book-list').append(data);
    	        }
            });
    	}
    });
    $('button.fav').click(function(e){
		e.preventDefault();
		var div = $(this).closest("div");
		$.post('{% url "add_fav" %}',
			{
				id: $(this).data('id'),
				action: $(this).data('action')
			},
			function(data){
				if (data['status'] == 'ok') {
					var previous_action = $('button.fav', div).data('action');
					// toggle data-action
					$('button.fav', div).data('action',
					previous_action == 'fav' ? 'unfav' : 'fav');
					// toggle link text
					$('button.fav', div).text(
					previous_action == 'fav' ? 'Remove from favourites' : 'Add to favourites');
					// update total followers
					var previous_favers = parseInt(
					$('span.count .total', div).text());
					$('span.count .total', div).text(previous_action == 'fav' ?
					previous_favers + 1 : previous_favers - 1);
					if (previous_action == 'fav') {
						$('button.fav', div).removeClass('custom-green');
						$('button.fav', div).addClass('custom-red');
					}
          			else {
						$('button.fav', div).removeClass('custom-red');
						$('button.fav', div).addClass('custom-green');
					}

				}
			}
		);
	});
{% endblock %}